# Generated by Django 5.1.6 on 2025-02-06 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'verbose_name': '----Empleado----', 'verbose_name_plural': '-----Empleados----'},
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cargo',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('vendedor', 'Vendedor'), ('cajero', 'Cajero'), ('supervisor', 'supervisor'), ('limpieza', 'limpieza'), ('seguridad', 'seguridad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
